interface BibleChaptersInterface {
  [key: string]: number
}
const bibleChapters: BibleChaptersInterface = {
  'Genesis': 50,
  'Exodus': 40,
  'Leviticus': 27,
  'Numbers': 36,
  'Deuteronomy': 34,
  'Joshua': 0,
  'Judges': 0,
  'Ruth': 0,
  '1 Samuel': 0,
  '2 Samuel': 0,
  '1 Kings': 0,
  '2 Kings': 0,
  '1 Chronicles': 0,
  '2 Chronicles': 0,
  'Ezra': 0,
  'Nehemiah': 0,
  'Esther': 0,
  'Job': 0,
  'Psalms': 0,
  'Proverbs': 0,
  'Ecclesiastes': 0,
  'Song of Solomon': 0,
  'Isaiah': 0,
  'Jeremiah': 0,
  'Lamentations': 0,
  'Ezekiel': 0,
  'Daniel': 0,
  'Hosea': 0,
  'Joel': 0,
  'Amos': 0,
  'Obadiah': 0,
  'Jonah': 0,
  'Micah': 0,
  'Nahum': 0,
  'Habakkuk': 0,
  'Zephaniah': 0,
  'Haggai': 0,
  'Zechariah': 0,
  'Malachi': 0,
  'Matthew': 0,
  'Mark': 0,
  'Luke': 0,
  'John': 0,
  'Acts (of the Apostles)': 0,
  'Romans': 0,
  '1 Corinthians': 0,
  '2 Corinthians': 0,
  'Galatians': 0,
  'Ephesians': 0,
  'Philippians': 0,
  'Colossians': 0,
  '1 Thessalonians': 0,
  '2 Thessalonians': 0,
  '1 Timothy': 0,
  '2 Timothy': 0,
  'Titus': 0,
  'Philemon': 0,
  'Hebrews': 0,
  'James': 0,
  '1 Peter': 0,
  '2 Peter': 0,
  '1 John': 0,
  '2 John': 0,
  '3 John': 0,
  'Jude': 0,
  'Revelation': 0
}

export { bibleChapters }